'''
Columns names for Highways England Network Shapefile
'''

CLASS_NAME = "CLASS_NAME"
ROAD_NUMBER = "ROA_NUMBER"
SECT_LABEL = "SECT_LABEL"
LOCATION = "LOCATION"
START_DATE = "START_DATE"
S_END_DATE = "S_END_DATE"
SEC_LENGTH = "SEC_LENGTH"
FUNCT_NAME = "FUNCT_NAME"
AREA_NAME = "AREA_NAME"
DIRECTION = "DIREC_CODE"
NO_OF_LANES = "PERM_LANES"
LANE_TYPE = "DUAL_NAME"
ENVIRONMENT = "ENVIR_NAME"
AUTHORITY = "AUTHO_NAME"
REF_NO = "REFERENCE"